"""'rename_internship_to_job_add_fields'

Revision ID: 05024e55a6bb
Revises: b1990ad76f8e
Create Date: 2025-10-03 12:47:57.845424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05024e55a6bb'
down_revision: Union[str, Sequence[str], None] = 'b1990ad76f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internships_id'), table_name='internships')
    op.drop_table('internships')
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('job_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('applications_internship_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'])
    op.drop_column('applications', 'internship_id')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.add_column('applications', sa.Column('internship_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_internship_id_fkey'), 'applications', 'internships', ['internship_id'], ['id'])
    op.drop_column('applications', 'job_id')
    op.drop_column('applications', 'status')
    op.create_table('internships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('internships_pkey'))
    )
    op.create_index(op.f('ix_internships_id'), 'internships', ['id'], unique=False)
    # ### end Alembic commands ###
