"""update internship fields and the text used for scoring

Revision ID: 23ebadea3b27
Revises: 3a04fe72e1e3
Create Date: 2025-09-26 13:52:40.796283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ebadea3b27'
down_revision: Union[str, Sequence[str], None] = '3a04fe72e1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
