"""update internship fields

Revision ID: 3a04fe72e1e3
Revises: 73f32582a29e
Create Date: 2025-09-26 13:43:18.013170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a04fe72e1e3'
down_revision: Union[str, Sequence[str], None] = '73f32582a29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('location', sa.String(), nullable=True))
    op.add_column('internships', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('internships', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('internships', sa.Column('deadline', sa.Date(), nullable=True))
    op.drop_column('internships', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('internships', 'deadline')
    op.drop_column('internships', 'requirements')
    op.drop_column('internships', 'duration')
    op.drop_column('internships', 'location')
    # ### end Alembic commands ###
