"""add unique constraints for phone and linkedin per job

Revision ID: 9c06620ed329
Revises: 47fa30d14db0
Create Date: 2025-10-07 13:34:46.553188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c06620ed329'
down_revision: Union[str, Sequence[str], None] = '47fa30d14db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_job_linkedin_application', 'applications', ['job_id', 'linkedin_url'])
    op.create_unique_constraint('unique_job_phone_application', 'applications', ['job_id', 'phone_number'])
    op.create_unique_constraint('unique_user_job_application', 'applications', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_job_application', 'applications', type_='unique')
    op.drop_constraint('unique_job_phone_application', 'applications', type_='unique')
    op.drop_constraint('unique_job_linkedin_application', 'applications', type_='unique')
    # ### end Alembic commands ###
