"""Add form fields to applications table

Revision ID: abd9bc51d2e9
Revises: a658f99e7651
Create Date: 2025-10-05 14:08:05.295433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd9bc51d2e9'
down_revision: Union[str, Sequence[str], None] = 'a658f99e7651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('cover_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'cover_letter')
    op.drop_column('applications', 'linkedin_url')
    op.drop_column('applications', 'years_experience')
    op.drop_column('applications', 'education_level')
    op.drop_column('applications', 'phone_number')
    op.drop_column('applications', 'full_name')
    # ### end Alembic commands ###
