"""add role to user

Revision ID: f31451397a7f
Revises: 05024e55a6bb
Create Date: 2025-10-03 13:55:48.960094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31451397a7f'
down_revision: Union[str, Sequence[str], None] = '05024e55a6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'])
    op.drop_column('applications', 'internship_id')
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.add_column('applications', sa.Column('internship_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'job_id')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
